openapi: 3.0.3
info:
  title: CanDIG-API
  version: 0.1.0
servers:
  - url: /v3
security:
  - {}
paths:
  /service-info:
    get:
      summary: Retrieve information about this service
      description: Returns information about the query service
      operationId: query_operations.get_service_info
      responses:
        200:
          description: Retrieve info about the Query service
          content:
            application/json:
              schema:
                type: object