-- OMOP CDM Schema for sql testing phenopacket_operations.py
-- Only includes tables and columns referenced by the SQL queries.

CREATE SCHEMA IF NOT EXISTS omop;
CREATE SCHEMA IF NOT EXISTS candig;

CREATE TABLE omop.concept (
    concept_id          INTEGER PRIMARY KEY,
    concept_name        VARCHAR(255),
    domain_id           VARCHAR(20),
    vocabulary_id       VARCHAR(20),
    concept_class_id    VARCHAR(20),
    concept_code        VARCHAR(50)
);

CREATE TABLE omop.concept_ancestor (
    ancestor_concept_id     INTEGER NOT NULL,
    descendant_concept_id   INTEGER NOT NULL,
    min_levels_of_separation INTEGER,
    max_levels_of_separation INTEGER,
    PRIMARY KEY (ancestor_concept_id, descendant_concept_id)
);

CREATE TABLE omop.person (
    person_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender_concept_id       INTEGER,
    year_of_birth           INTEGER,
    month_of_birth          INTEGER,
    day_of_birth            INTEGER,
    birth_datetime          TIMESTAMP,
    race_concept_id         INTEGER,
    ethnicity_concept_id    INTEGER,
    location_id             INTEGER,
    provider_id             INTEGER,
    care_site_id            INTEGER,
    person_source_value     VARCHAR(50),
    gender_source_value     VARCHAR(50),
    gender_source_concept_id INTEGER,
    race_source_value       VARCHAR(50),
    race_source_concept_id  INTEGER,
    ethnicity_source_value  VARCHAR(50),
    ethnicity_source_concept_id INTEGER
);

CREATE TABLE omop.death (
    person_id           INTEGER NOT NULL,
    death_date          DATE,
    death_datetime      TIMESTAMP,
    death_type_concept_id INTEGER,
    cause_concept_id    INTEGER,
    cause_source_value  VARCHAR(50),
    cause_source_concept_id INTEGER
);

CREATE TABLE omop.episode (
    episode_id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id                   INTEGER NOT NULL,
    episode_concept_id          INTEGER,
    episode_start_date          DATE,
    episode_start_datetime      TIMESTAMP,
    episode_end_date            DATE,
    episode_end_datetime        TIMESTAMP,
    episode_parent_id           INTEGER,
    episode_number              INTEGER,
    episode_object_concept_id   INTEGER,
    episode_type_concept_id     INTEGER,
    episode_source_value        VARCHAR(50),
    episode_source_concept_id   INTEGER
);

CREATE TABLE omop.episode_event (
    episode_id                          INTEGER NOT NULL,
    event_id                            INTEGER NOT NULL,
    episode_event_field_concept_id      INTEGER
);

CREATE TABLE omop.condition_occurrence (
    condition_occurrence_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id                   INTEGER NOT NULL,
    condition_concept_id        INTEGER,
    condition_start_date        DATE,
    condition_start_datetime    TIMESTAMP,
    condition_end_date          DATE,
    condition_end_datetime      TIMESTAMP,
    condition_type_concept_id   INTEGER,
    condition_status_concept_id INTEGER,
    stop_reason                 VARCHAR(20),
    provider_id                 INTEGER,
    visit_occurrence_id         INTEGER,
    visit_detail_id             INTEGER,
    condition_source_value      VARCHAR(50),
    condition_source_concept_id INTEGER,
    condition_status_source_value VARCHAR(50)
);

CREATE TABLE omop.observation (
    observation_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id                   INTEGER NOT NULL,
    observation_concept_id      INTEGER,
    observation_date            DATE,
    observation_datetime        TIMESTAMP,
    observation_type_concept_id INTEGER,
    value_as_number             NUMERIC,
    value_as_string             VARCHAR(60),
    value_as_concept_id         INTEGER,
    qualifier_concept_id        INTEGER,
    unit_concept_id             INTEGER,
    provider_id                 INTEGER,
    visit_occurrence_id         INTEGER,
    visit_detail_id             INTEGER,
    observation_source_value    VARCHAR(50),
    observation_source_concept_id INTEGER,
    unit_source_value           VARCHAR(50),
    qualifier_source_value      VARCHAR(50),
    value_source_value          VARCHAR(50),
    observation_event_id        INTEGER,
    obs_event_field_concept_id  INTEGER
);

CREATE TABLE omop.measurement (
    measurement_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id                   INTEGER NOT NULL,
    measurement_concept_id      INTEGER,
    measurement_date            DATE,
    measurement_datetime        TIMESTAMP,
    measurement_time            VARCHAR(10),
    measurement_type_concept_id INTEGER,
    operator_concept_id         INTEGER,
    value_as_number             NUMERIC,
    value_as_concept_id         INTEGER,
    unit_concept_id             INTEGER,
    range_low                   NUMERIC,
    range_high                  NUMERIC,
    provider_id                 INTEGER,
    visit_occurrence_id         INTEGER,
    visit_detail_id             INTEGER,
    measurement_source_value    VARCHAR(50),
    measurement_source_concept_id INTEGER,
    unit_source_value           VARCHAR(50),
    unit_source_concept_id      INTEGER,
    value_source_value          VARCHAR(50),
    measurement_event_id        INTEGER,
    meas_event_field_concept_id INTEGER
);

CREATE TABLE omop.specimen (
    specimen_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id                   INTEGER NOT NULL,
    specimen_concept_id         INTEGER,
    specimen_type_concept_id    INTEGER,
    specimen_date               DATE,
    specimen_datetime           TIMESTAMP,
    quantity                    NUMERIC,
    unit_concept_id             INTEGER,
    anatomic_site_concept_id    INTEGER,
    disease_status_concept_id   INTEGER,
    specimen_source_id          VARCHAR(50),
    specimen_source_value       VARCHAR(50),
    unit_source_value           VARCHAR(50),
    anatomic_site_source_value  VARCHAR(50),
    disease_status_source_value VARCHAR(50)
);

CREATE TABLE omop.drug_exposure (
    drug_exposure_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id                   INTEGER NOT NULL,
    drug_concept_id             INTEGER,
    drug_exposure_start_date    DATE,
    drug_exposure_start_datetime TIMESTAMP,
    drug_exposure_end_date      DATE,
    drug_exposure_end_datetime  TIMESTAMP,
    verbatim_end_date           DATE,
    drug_type_concept_id        INTEGER,
    stop_reason                 VARCHAR(20),
    refills                     INTEGER,
    quantity                    NUMERIC,
    days_supply                 INTEGER,
    sig                         TEXT,
    route_concept_id            INTEGER,
    lot_number                  VARCHAR(50),
    provider_id                 INTEGER,
    visit_occurrence_id         INTEGER,
    visit_detail_id             INTEGER,
    drug_source_value           VARCHAR(255),
    drug_source_concept_id      INTEGER,
    route_source_value          VARCHAR(50),
    dose_unit_source_value      VARCHAR(50)
);

CREATE TABLE omop.procedure_occurrence (
    procedure_occurrence_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id                   INTEGER NOT NULL,
    procedure_concept_id        INTEGER,
    procedure_date              DATE,
    procedure_datetime          TIMESTAMP,
    procedure_end_date          DATE,
    procedure_end_datetime      TIMESTAMP,
    procedure_type_concept_id   INTEGER,
    modifier_concept_id         INTEGER,
    quantity                    INTEGER,
    provider_id                 INTEGER,
    visit_occurrence_id         INTEGER,
    visit_detail_id             INTEGER,
    procedure_source_value      VARCHAR(255),
    procedure_source_concept_id INTEGER,
    qualifier_source_value      VARCHAR(50),
    modifier_source_value       VARCHAR(50)
);

CREATE TABLE candig.person_in_dataset (
    dataset_id  VARCHAR(50) NOT NULL,
    person_id   INTEGER NOT NULL,
    PRIMARY KEY (dataset_id, person_id)
);
